### ISSUE TITLE
Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by Xaenchan** [louisefindlay23/youtubecommunitybot#4]
```
npm start

> youtubecommunitybot@1.0.0 start
> node bot.js

Ready!
TypeError: Cannot read properties of undefined (reading '0')
    at .\bot.js:28:50
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
getting this error .env should be fine i think

BOT_TOKEN=(used one i had for another bot and a new one)
SERVER_ID=(both IDs should be one my bot got invited to)
CHANNEL_ID=(both IDs should be one my bot got invited to)
YT_API_URL=https://yt.lemnoslife.com/channels?part=community&id=(tried with 2 who had community posts)
YT_CHANNEL_ID=(tried with 2 who had community posts)

**Comment by louisefindlay23** [comment]
Hi, @Xaenchan. 

Thanks for trying out this project. 

The error messages shows up on line 28 which should be the `communityPosts` variable. Have you tried `console.log(data)` to see if the API is returning anything?

**Comment by CatharsisRobb** [comment]
```
/home/robb/Documents/AiChan/node_modules/discord.js/src/client/Client.js:214
    if (!token || typeof token !== 'string') throw new DiscordjsError(ErrorCodes.TokenInvalid);
                                                   ^

Error [TokenInvalid]: An invalid token was provided.
    at Client.login (/home/robb/Documents/AiChan/node_modules/discord.js/src/client/Client.js:214:52)
    at Object.<anonymous> (/home/robb/Documents/AiChan/bot.js:120:8)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'TokenInvalid'
}
```
Hey! I'm getting a similar token issue and I'm not really sure whats going on. To be honest I'm still a budding hobbyist and I think my issue lands in the Youtube Operational API. I read everything I could on it, including the formatting from the creator of this thread, and I still am not sure what exactly I'm missing, though it's probably something really stupid haha. For noobies like me the formatting of what to put where is unclear from their public documentation, though I tried a few things from my Channel ID to my Youtube v3 API key to no avail. Any ideas? I know the rest of my tokens are correct (I have a few other local discord bots already, so I'm not a _complete_ idiot :P)

**Comment by louisefindlay23** [comment]
Hi, @CatharsisDrums. Thanks for trying this out.

The error message seems to be related to Discord.js token. What does line 120 of `bot.js` look like?

**Comment by CatharsisRobb** [comment]
`client.login(token);` is the only thing there. For clarity's sake everything is in the same folder so it shouldn't be a lack of _finding_ the .env at least.

**Comment by louisefindlay23** [comment]
> `client.login(token);` is the only thing there. For clarity's sake everything is in the same folder so it shouldn't be a lack of _finding_ the .env at least.

Does the token `console.log` correctly? @CatharsisRobb

**Comment by CatharsisRobb** [comment]
Admittedly I'm not sure. One of those details I've never had to mess with, so I'm not entirely sure how to check. Here's what I tried though: 

- Adding `console.log("Hello world!");` at the end of bot.js -- output "hello world" correctly
- Adding `console.log()` to the end of bot.js -- no change to original console output
- Adding `console.log(token)` to the end of bot.js  -- spits out `undefined`
- Added each to the .env knowing that would do nothing -- big shocker, no affect lmao

All attempts were still followed by the same error output as my first post. Obviously I'm still new to this, so it's very possible I'm just not implementing anything properly, but otherwise the terminal only displays what I pasted in my first post. Feel free to let me know if I'm actually just stupid haha

**Comment by louisefindlay23** [comment]
Thanks, @CatharsisRobb. The error seems to be with your undefined `token` variable. 

Have you defined it before your code to read the token? What does the `token` variable look like?

**Comment by CatharsisRobb** [comment]
I left all the code default, so `const token = process.env.BOT_TOKEN;` and all other `process.env` defaults in bot.js are intact. I created a `tokens.env` using your guide and all tokens/IDs within should be correct. On the surface, it should read the .env fine, but it feels like it just isn't choosing to for some reason.

**Comment by louisefindlay23** [comment]
@CatharsisRobb, try renaming `tokens.env` to `.env`

**Comment by CatharsisRobb** [comment]
Unfortunately no change,

Edit: there is a hidden `.gitignore` file that has `.env /node_modules/ lastPostID.json` listed in it. Not sure if any of that is relevant but figured I'd mention it since I found it (didn't have hidden files enabled for some reason, I usually do  lmao)

**Comment by louisefindlay23** [comment]
@CatharsisRobb, do you have a public GitHub repo with your code?

**Comment by CatharsisRobb** [comment]
No, but aside from changing the token values in the `.env` it's all the base code cloned directly from your repo on here

**Comment by louisefindlay23** [comment]
@CatharsisRobb, do you have the `dotenv` npm package installed and the import dotenv line at the beginning?

**Comment by CatharsisRobb** [comment]
`require("dotenv").config();` is at the beginning and I do have the package installed. If I swap it out for `import 'dotenv/config'` it throws a syntax error.

**Comment by louisefindlay23** [comment]
@CatharsisRobb, have you tried manually defining the token? So `const token = DiscordBotToken`

**Comment by CatharsisRobb** [comment]
OK! - that wasn't it but in trying it and getting a reference error I found a settting that had changed since the last time I'd set up a bot with Discord's Dev Portal and was basically breaking it. It boots up now!

BUT - now I'm having the exact error the OP had:
`TypeError: Cannot read properties of undefined (reading '0')
    at /home/robb/youtubecommunitybot/bot.js:28:50
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
` which points to the open bracket in this line: `const communityPosts = data.items[0].community;`

adding `console.log(data)` to the code like you asked OP just returns `Data Not Defined` so I've got a feeling I'm doing that incorrectly. So far I'm just happy it's booting at all and I can see the bot in my server members list

**Comment by louisefindlay23** [comment]
@CatharsisRobb, that's great. Can you `console.log(URL)` to see if your YT API URL is picked up correctly?

**Comment by CatharsisRobb** [comment]
Sorry for the long wait, I was on a business trip away from the host PC. Here's what adding `console.log(URL)` gave me:
```

> youtubecommunitybot@1.0.0 start
> node bot.js

[class URL] {
  canParse: [Function: canParse],
  createObjectURL: [Function: createObjectURL],
  revokeObjectURL: [Function: revokeObjectURL]
}
Ready!
TypeError: Cannot read properties of undefined (reading '0')
    at /home/robb/youtubecommunitybot/bot.js:28:50
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by louisefindlay23** [comment]
Thanks, @CatharsisRobb. That's strange. Can you show me what URL is defined as?

**Comment by CatharsisRobb** [comment]
```
// YT API URL for Community Posts with Channel ID
    const URL = `${process.env.YT_API_URL}${process.env.YT_CHANNEL_ID}`;
```
and in the .env:
```
YT_API_URL=https://yt.lemnoslife.com/channels?part=community&id=UCCr6o95ER0BY_6-P2Xq0tZQ
YT_CHANNEL_ID=UCCr6o95ER0BY_6-P2Xq0tZQ
```
I'm not concerned over my channel ID being in that paste. It's not like it isn't public 
The lemnoslife process _**was**_ pretty confusing to me. I did my best to get it correct, but I wouldn't be shocked if I have it completely wrong. The site's "instructions" are about as clear as a brick wall if you aren't already very familiar with APIs (which I am not haha)

**Comment by louisefindlay23** [comment]
@CatharsisRobb, try adding the URL directly rather than using dotenv.

**Comment by CatharsisRobb** [comment]
Doing that gave me
```
File read failed: [Error: ENOENT: no such file or directory, open './lastPostID.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './lastPostID.json'
}
```

**Comment by louisefindlay23** [comment]
@CatharsisRobb, that's good. You're one step closer. What directory have you stored your project in? Is it a protected directory that requires admin access?

**Comment by CatharsisRobb** [comment]
It's in my home directory. That's just where it defaulted when I cloned the repo and there shouldn't be admin locks on it. Just to be sure, here's the folder permissions.
![Screenshot from 2024-09-18 12-43-38](https://github.com/user-attachments/assets/58cfa72e-fa3f-4c14-ad71-be2bc6386ef7)

**Comment by louisefindlay23** [comment]
Okay. Try creating a blank lastPostID.json file, @CatharsisRobb.

**Comment by CatharsisRobb** [comment]
Made it, got this in the output
```
[class URL] {
  canParse: [Function: canParse],
  createObjectURL: [Function: createObjectURL],
  revokeObjectURL: [Function: revokeObjectURL]
}
Ready!
undefined:2


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /home/robb/youtubecommunitybot/bot.js:38:43
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

Node.js v18.19.1
```

**Comment by louisefindlay23** [comment]
Try nesting `newPostID = JSON.parse(newPostID);` in an if statement so `if (newPostID)`.

**Comment by CatharsisRobb** [comment]
ok so I nested newPostID AND lastPostID into this:
```
else { 
if (lastPostID) lastPostID = JSON.parse(lastPostID);
if (newPostID) newPostID = JSON.parse(newPostID);
console.info(`ID of previous post is: ${lastPostID}`);
console.info(`ID of latest post is: ${newPostID}`);
                        
```
I did this because doing it _only_ for `newPostID` spat an error out. I'm not positive this is the syntax you meant, but it ran the bot with no errors after posting `Ready!` until I made a community post to test it. Below is the tech support gore it spit back at me lmao

```
AxiosError: connect ETIMEDOUT 129.151.245.17:443
    at AxiosError.from (/home/robb/youtubecommunitybot/node_modules/axios/dist/node/axios.cjs:876:14)
    at RedirectableRequest.handleRequestError (/home/robb/youtubecommunitybot/node_modules/axios/dist/node/axios.cjs:3156:25)
    at RedirectableRequest.emit (node:events:517:28)
    at eventHandlers.<computed> (/home/robb/youtubecommunitybot/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/home/robb/youtubecommunitybot/node_modules/axios/dist/node/axios.cjs:4269:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  port: 443,
  address: '129.151.245.17',
  syscall: 'connect',
  code: 'ETIMEDOUT',
  errno: -110,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': undefined,
      'User-Agent': 'axios/1.7.5',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'get',
    url: 'https://yt.lemnoslife.com/channels?part=community&id=UCCr6o95ER0BY_6-P2Xq0tZQ',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/channels?part=community&id=UCCr6o95ER0BY_6-P2Xq0tZQ',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'yt.lemnoslife.com',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/channels',
      search: '?part=community&id=UCCr6o95ER0BY_6-P2Xq0tZQ'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /channels?part=community&id=UCCr6o95ER0BY_6-P2Xq0tZQ HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.7.5\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: yt.lemnoslife.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/channels?part=community&id=UCCr6o95ER0BY_6-P2Xq0tZQ',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'yt.lemnoslife.com',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://yt.lemnoslife.com/channels?part=community&id=UCCr6o95ER0BY_6-P2Xq0tZQ',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ETIMEDOUT 129.151.245.17:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1549:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '129.151.245.17',
    port: 443
  }
}
```

**Comment by louisefindlay23** [comment]
@CatharsisRobb, try self-hosting the YouTube operational API. https://github.com/Benjamin-Loison/YouTube-operational-API

**Comment by CatharsisRobb** [comment]
Self-hosting didn't seem to change anything, I actually got this again, which is odd because that  didn't happen before the self-host:
```
undefined:2


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /home/robb/youtubecommunitybot/bot.js:38:59
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```
